events {}

http {
    server {
        listen 80;

        location /metrics {
            auth_basic "Metrics";
            auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://api:5000/metrics;
        }

        location / {
            proxy_pass http://api:5000;
        }

    }
}