- name: Setup server
  hosts: all
  become: true
  remote_user: ubuntu

  roles:
    - role: geerlingguy.docker
      tags: infra

  tasks:
    - name: Copy docker-compose file
      copy:
        src: ../../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      tags: deploy

    - name: Create .env file
      copy:
        content: |
          DB_USER={{ lookup('ansible.builtin.env', 'DB_USER') }}
          DB_PASSWORD={{ lookup('ansible.builtin.env', 'DB_PASSWORD') }}
        dest: /home/ubuntu/.env
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      tags: infra

    - name: Copy NGINX configuration
      copy:
        src: ../../nginx.conf
        dest: /home/ubuntu/nginx.conf
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      tags: infra
    
    - name: Create Nginx password file
      copy:
        content: "{{ lookup('ansible.builtin.env', 'NGINX_AUTH_STRING') }}"
        dest: /home/ubuntu/.htpasswd
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      tags: deploy

    - name: Copy Prometheus configuration
      copy:
        src: ../../prometheus.yml
        dest: /home/ubuntu/prometheus.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      tags: infra

    - name: Login to GitHub Container Registry
      community.docker.docker_login:
        registry: ghcr.io
        username: "{{ lookup('ansible.builtin.env', 'GHCR_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'GHCR_TOKEN') }}"
      tags: deploy

    - name: Run docker-compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: present
        pull: always
      register: output
      tags: deploy