- name: Setup server
  hosts: all
  become: true
  remote_user: ubuntu

  roles:
    - role: geerlingguy.docker
      tags: infra

  tasks:
    - name: Copy docker-compose file
      copy:
        src: ../../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      tags: deploy

    - name: Create .env file
      copy:
        content: |
          DB_USER={{ db_user }}
          DB_PASSWORD={{ db_password }}
        dest: /home/ubuntu/.env
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      tags: infra

    - name: Copy NGINX configuration
      copy:
        src: ../../nginx.conf
        dest: /home/ubuntu/nginx.conf
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      tags: infra
    
    - name: Login to GitHub Container Registry
      community.docker.docker_login:
        registry: ghcr.io
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_token }}"
      tags: deploy

    - name: Run docker-compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: present
        pull: always
      register: output
      tags: deploy