name: CD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'infra/**'
      - 'README.md'

permissions:
  contents: read
  packages: write

jobs:
  build:
  
    runs-on: ubuntu-latest 
  
    steps:
    - uses: actions/checkout@v6
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/naturdex/naturdex-backend:latest

    - name: Push Docker image
      run: docker push ghcr.io/naturdex/naturdex-backend:latest

  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Install Ansible
          run: pip install ansible

        - name: Setup SSH Agent
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Run Deploy Playbook
          working-directory: infra/ansible
          run: |
            ansible-playbook \
              -i "${{ secrets.APP_SERVER_IP }}," \
              -u ubuntu \
              --ssh-extra-args="-o StrictHostKeyChecking=no" \
              --tags "deploy" \
              -e "ghcr_username=${{ github.actor }} ghcr_token=${{ secrets.GITHUB_TOKEN }}" \
              playbook.yml